services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - registry_data:/var/lib/registry
      - ./auth:/auth
    restart: always
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd

  registry-ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - "5050:80"
    environment:
      - REGISTRY_TITLE=My Registry
      - REGISTRY_URL=http://localhost:5000
    depends_on:
      - registry

  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  registry_data:
  portainer_data: